
### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 5,
  "accountNumber": "1104542775",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 5,
  "accountNumber": "1104542775",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "4d1063ead21344818ece5eea0c69ca90",
  "accountNumber": "1104542775",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/ef3ef25594204dfda256ff958f2003fd